services:
  airflow:
    image: apache/airflow:2.9.3-python3.11
    container_name: retail-orders-airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      PROJECT_DIR: /opt/airflow/project
      DBT_PROFILES_DIR: /opt/airflow/project/dbt
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: ${S3_PREFIX:-retail_orders}
    volumes:
      - ./:/opt/airflow/project
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db migrate &&
      airflow users create --username admin --password admin --firstname Alan --lastname Portfolio --role Admin --email admin@example.com || true &&
      airflow standalone"
